Documents/BLOG3django/blog/urls.py
from django.urls import path
from .views import PublicationListView, PublicationDetailView

urlpatterns = [
    path('', PublicationListView.as_view(), name='publications-list'),
    path('publication/<int:pk>/', PublicationDetailView.as_view(), name='publication-detail'),
]

Documents/BLOG3django/django_project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), #agregamos la url de la app blog	
    
]

Documents/BLOG3django/blog/models.py
from django.db import models

# Create your models here.
class Publication(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=1000)
    author= models.ForeignKey('auth.User', on_delete=models.CASCADE)
    date= models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.title

Documents/BLOG3django/blog/views.py
#from django.shortcuts import render
from .models import Publication
from django.views.generic import ListView, DetailView

class PublicationListView(ListView):
    model = Publication
    template_name = 'publications-list.html'
    
# se agrego la nueva clase    
class PublicationDetailView(DetailView):
    model = Publication
    template_name = 'publication-detail.html'   

# Create your views here.

Documents/BLOG3django/templates/Publications-list.html
{% extends "_base.html" %}


{% block content %}
{% for post in publication_list %}
    <a href=" {% url 'publication-detail' post.pk %}" ><h2>{{ post.title }}</h2></a>
    <p>{{ post.author }}</p>
    <p>{{ post.date }}</p>
    <p>{{ post.content }}</p>
    
{% endfor %}
{% endblock content %}

Documents/BLOG3django/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>DJANGO blog</title>
</head>
<body>
  <HEAder> 
   <h1> <a href="{% url 'publications-list' %}">Blog de Josefino</a></h1>
  </HEAder> 
  {% block content %} 
      
  {% endblock content %} 
</body>
</html>

Documents/BLOG3django/templates/publication-detail.html
{% extends "_base.html" %}


{% block content %}
    <h2>{{ publication.title }}</h2>
    <p>{{ publication.author }}</p>
    <p>{{ postpublication.body }}</p>
    

{% endblock content %}